# Generated by Django 4.1.3 on 2022-12-29 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('image', models.ImageField(upload_to='Image', verbose_name='تصویر ')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='آدرس')),
            ],
        ),
    ]
